# Theme
theme = 'catppuccin_frappe'

# General Helix's configuration
[editor]
auto-completion = true
auto-format = true
auto-info = true
auto-save = false
bufferline = 'always'
color-modes = true
completion-trigger-len = 1
cursorline = true
cursorcolumn = false
idle-timeout = 50
line-number = 'relative'
mouse = false
scroll-lines = 1
scrolloff = 3
shell = ['pwsh']
true-color = true
insert-final-newline = false
popup-border = 'menu'

# Auto-pairs
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true
goto-reference-include-declaration = true

[editor.statusline]
left = ["mode", "read-only-indicator", "spinner"]
center = ["file-name", "diagnostics", "workspace-diagnostics"]
right = [  "selections",  "position",  "position-percentage", "spacer", "total-line-numbers",  "spacer",  "version-control",]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
parents = false
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]

tab = "→"
tabpad = "·" # tab空格会显示： "→···" (依赖于tab宽度)

[editor.soft-wrap]
enable = false
max-wrap = 25              # 增加该值可以降低强制从一个词中间软换行
max-indent-retain = 0
wrap-indicator = "↪"
wrap-at-text-width = false

[editor.smart-tab]
enable = true
supersede-menu = true

[keys.normal]
space = { q = ":q", w = ":w", x = ":x", Q = ":q!"}
C-h = "move_prev_word_end"
C-l = "move_next_word_start"
C-a = "select_all"
C-c = "yank_joined_to_clipboard"
C-v = "paste_clipboard_after"

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.insert]
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
A-k = "move_line_up"
A-j = "move_line_down"
C-t = "indent"
C-d = "unindent"
